### ISSUE TITLE
Update to latest version of swagger

### ISSUE THREAD

**Issue by bbaugher** [cerner/beadledom#29]
Currently beadledom uses [1.3.12](https://github.com/swagger-api/swagger-core/tree/v1.3.12) which is over 2 years old. They have then re-named themselves (group id) to io.swagger and are up to 1.5.13.

They talk about [compatibility](https://github.com/swagger-api/swagger-core#compatibility) but I'm guessing that has to do with the API data vs the class compatibility. Though its only 2 minor version bumps up all the classes seemed to have been re-named to io.swagger.

**Comment by johnlcox** [comment]
This is something we want to do, but it's currently blocked by an internal tool that is dependent on the swagger 1.x for it's UI. Once that internal tool has been uplifted it should be backward compatible and allow us to uplift to the newer swagger.

We also need to keep an eye on Open API 3.0 which may be released sometime this year.

**Comment by mkwhitacre** [comment]
non-passive dependency upgrades are one of the significant reasons major versions exist.  Why can't you release 2.x of beadledom for consumers not affected/concerned with your internal tool?  Your internal tool can be maintained on the 1.x code stream.

**Comment by johnlcox** [comment]
We could definitely bump the major version. If we are wanting to do that we'll want to try to group any other non-passive changes together and have them all be released together.

A major blocker to going to swagger 2 is that we'll need to make some major pull requests to swagger-core to support JAX-RS 2 and Resteasy. It currently only supports JAX-RS1/Resteasy or Jersey2 [1].

It looks like they've closed that issue and don't plan to do the project restructuring until Swagger 3, so that may be a complete blocker for this.

[1] https://github.com/swagger-api/swagger-core/issues/1244

**Comment by johnlcox** [comment]
I have started a swagger3 branch, but it likely won't be part of the 3.0 release. However, the Open API 3 Java implementation uses totally different packages from Swagger 1, so we should be able to add Open API 3 support in a future release passively.

We will also remove Swagger 1 as a default installed feature with the 3.0 release so that services built with 3.x can choose which Swagger/Open API version to use and possibly even support both in a single service.

**Comment by johnlcox** [comment]
Upgraded to swagger 2 in #119.
