### ISSUE TITLE
Update Stagemonitor to not be included by default

### ISSUE THREAD

**Issue by shiftyeyes** [cerner/beadledom#50]
I am trying to consume Beadledom with a different APM than Stagemonitor. Currently Stagemonitor is included in the BeadledomModule [1]. Would you consider a PR that removes Stagemonitor from BeadledomModule, and make consumers add the StagemonitorModule [2] directly if they want to use Stagemonitor? Or maybe create additional modules that would also include StagemonitorModule like the current BeadledomModule.

[1] 
https://github.com/cerner/beadledom/blob/master/core/src/main/java/com/cerner/beadledom/core/BeadledomModule.java
[2] https://github.com/cerner/beadledom/blob/master/stagemonitor/src/main/java/com/cerner/beadledom/stagemonitor/StagemonitorModule.java

**Comment by sparuvu** [comment]
That would be a non-passive change for the consumers. So, I feel like it's not a good idea.

**Comment by johnlcox** [comment]
I think we should try to target a 3.0 milestone release with 3 main things:

1. Remove stagemonitor from being installed by default.
1. Remove swagger 1 from being installed by default. This gives us the freedom to add an alternative OpenAPI 3 module without breaking things.
1. Switch from httpclient to okhttp and stop doing retries on all 500 errors (e.g. only retry on idempotent requests and 503s).

A fourth thing that might be worth doing is making what is installed more modular all around so that only the things that make sense for all services are installed by default but it's easy to add additional functionality by installing additional Guice modules.
