### ISSUE TITLE
Offset based pagination component

### ISSUE THREAD

**Issue by elliott311** [cerner/beadledom#51]
In a conversation with @johnlcox we have discussed a possibility of adding a common offset based pagination component to the beadledom. The component would decorate a list of objects returned from target methods with all necessary pagination elements.
 
Using John’s implementation of pagination as part of one of the Cerner projects as a model the component would include:

- a subclass of WriterInterceptor applied to target methods with a specific return type (e.g. 
   OffsetPaginatedList<T>)
- a response DTO decorated by the interceptor with:
    Items – list of items of type T
    totalResults – total number of results across all the pages
    hasMore - an indication wheter there are additional items on another page
    firstLink – link to the first page
    lastLink – link to the last page
    nextLink – link to a page after current (null if current is the last page)
    prevLink – link to a page before current (null if current is the first page)
 
I'm opening this issue to discuss design of the solution and feedback would be appreciated.

**Comment by johnlcox** [comment]
I think the `hasMore` field is not needed on the actual response object since that information can be derived by looking for a `nextLink`. The `hasMore` field should be present on the internal type that will be intercepted though since it can be used to determine the necessary links when total results may not be known.

`lastLink` should also be nullable since a last link can only exist in the case that total results are known.

One thing that needs to be decided is how to handle default values for the `limit` query parameter since that will be used for generating links when an explicit `limit` value is not set on a request.

**Comment by johnlcox** [comment]
Services are already duplicating the limit values between `@DefaultValue` and the swagger docs. The `@DefaultValue` is especially troublesome because it requires a `String` even though the limit param is usually a long or an int.

Since the value is already being duplicated it might be best to allow the `WriterInterceptor` to be injected with a value for the default pagination limit. Then each service could bind that limit to whatever they want, but make sure that it matches the swagger and JAX-RS values. Since it is a primitive type (`long`) it would need to be bound using a binding annotation.

**Comment by elliott311** [comment]
@DefaultValue is used by both jaxrs and swagger so I am not sure there is duplication.  If we were able to, via ResourceInfo, read the DefaultValue annotation value, we could avoid the need for injection of the value via a binding annotation.
The only limitation would be that the field would need to be named "limit" so that we could find the DefaultValue.
The other option would be to create a named binding that would be applied to the parameter that is the limit and then that parameter could have any arbitrary name but that feels like overkill.

**Comment by johnlcox** [comment]
Is there an example that could be linked on how `ResourceInfo` could be used? Could an instance of `ResourceInfo` be injected into a `WriterInterceptor` via the `@Contexst` of the request or did you have something else in mind?

**Comment by elliott311** [comment]
I was able to inject it using the @Context and the ResourceInfo has a way to get to the parameters and the parameter annotations.
    Annotation[][] resourceInfo1 = resourceInfo.getResourceMethod().getParameterAnnotations();
When I evaluated that it shows the following:
![screen shot 2017-09-22 at 8 44 51 am](https://user-images.githubusercontent.com/13615579/30744980-68ef758c-9f72-11e7-9b91-a97c409b2346.png)

We could then move through all of the parameters and find the one called "limit" and use the "DefaultValue" annotation to set the default limit. The only thing that would need to be looked into beyond that is...What do we do if they don't create a default value via the annotation.  Still have some research to do to verify we can tie them all together but I thought it was very promising.

**Comment by johnlcox** [comment]
That's pretty sweet that `ResourceInfo` can be injected using `@Context`. I looked in both the Resteasy and Jersey projects on github and it looks like both of them support injecting it, so we should be able to build this to be JAX-RS implementation agnostic.

I'm not sure we want to look for a parameter called "limit" as the means for finding the right default value. I can imagine other services, that might used beadledom, wanting to use "limit" for something besides pagination. 

Having a custom annotation for the pagination limit parameter is probably the safer approach. We could also have a fallback default that is used if the `@DefaultValue` parameter is not present. However, this may also require a custom annotation for the offset query parameter as well since we will need to be able to look up the actual query param values, if set, when generating the pagination links.

I'm not sure I'm a huge fan of needing two additional query params for any method that will use pagination. If we instead did want to use "limit" and "offset" I think we would have to provide a way to configure what those values are rather than having them hard coded. We could have "limit" and "offset" as defaults, but I think we are getting back to needing to inject those values somewhere.

**Comment by elliott311** [comment]
So here's what I was thinking about...

- Create two custom name bindings one for limit and one for offset which would serve as markers within the method that indicated which parameter was the limit and the offset.
- Then in the intercepter we can use the resourceinfo to find the markers and use them to resolve the parameter names as well as get the default values if also annotated.
- If the markers are not present in any of the query parameters, then we will look for "offset" and "limit" and use those.  This way they would only mark the parameters if they wished to have a parameter name other than "limit" or "offset".
- If the default value is not set via the annotations in the method then we can have a hard coded value behind the scenes.

I will be in big room planning on Monday but if we agree to continue down this path I will attempt to prioritize it for completion at the beginning of Q4.

**Comment by elliott311** [comment]
Something like this:
{code:java}      
    @ApiParam(value = "Paging parameter to retrieve specialty list starting at the given index."
              + " Must be greater than or equal to 0, default value of 0", allowableValues = "range[0, Infinity]")
       **@Offset** @DefaultValue("0") @QueryParam("offset") Integer offset,
      @ApiParam(
          value = "Paging parameter to limit the number of returned specialty list" +
              " Must be greater than or equal to 1 with a maximum value of 100, "
              + "default value of 20",
          allowableValues = "range[1, 100]")
      **@Limit** @DefaultValue("20") @QueryParam("limit") Integer limit {code}

**Comment by johnlcox** [comment]
I'm still not sure I like needing to add those two annotations everywhere. 

Is there anyway with JAX-RS to have those be used in place of `@QueryParam` and `@DefaultValue`? If we could combine those two into a single annotation for each pagination parameter that would be pretty amazing.

> If the markers are not present in any of the query parameters, then we will look for "offset" and "limit" and use those. This way they would only mark the parameters if they wished to have a parameter name other than "limit" or "offset".

We would also need to provide a mechanism to override the expected query parameter names.

**Comment by elliott311** [comment]
I have been able to create a common pagination implementation based on your project, added the stuff we talked about and was feeling pretty good about it - however, I ran into an issue in the beadledom based java client. 
The issue has to do with return type change in the interceptor. com.cerner.beadledom.client.proxy.GenericClientProxy uses reflection when determining how to deserialize the response json. 
From the method signature it is not getting OffsetPaginatedListDto<T> rather it gets OffsetPaginatedList<T> and therefore loses any fields that are not in the latter:
```java
ParameterizedType genericReturnType = (ParameterizedType)method.getGenericReturnType();
Type bodyType = genericReturnType.getActualTypeArguments()[0];
entity = response.readEntity(new GenericType(bodyType));
```
Considering that our endpoints are all returning a response of type GenericResponse we have to come up with some other way of determining the response type for response deserialization. 

Perhaps we can create an interface that OffsetPaginatedList would implement. We will then be able to use this interface to control the flow in GenericClientProxy::invoke and return an Object or have a field in this interface defining a return type. In either case it appears that we will need to make changes to GenericClientProxy to allow for response type change in the interceptor.

**Comment by johnlcox** [comment]
With the service we have been building we have started coming to the conclusion that it's not worth it to share a JAX-RS interface between the client and server.

* Pagination doesn't work as you mentioned
* `PATCH` will require a very different method signature on the server-side than the client-side
* Adding additional query params on the server-side is totally passive if they have a default, but is breaking for clients if an interface is shared

**Comment by elliott311** [comment]
OK.  We will have to put the pagination stuff on hold then until the client changes are in place and then re-visit it.

**Comment by lulzWill** [comment]
Hey @johnlcox and @elliott311, I've been working on a pagination implementation based largely off the work that @johnlcox had done with the addition of a BeanParam for easily adding and identifying the query params used for pagination. I also added some mechanisms to allow for configurable default limit/offset values as well as configurable field names. I've consumed the module in an internal project and it seems to be working pretty well, but I had a question about configurable field names within the BeanParam. Right now the BeanParam will always use "offset" and "limit" for the query parameter names since it is using the @QueryParam annotation to name the param. Because of this, if a consumer were to want to use a different field name, they would not be able to use the BeanParam in an intuitive way (and subsequently the convenience methods that come with it to use the configured default field values). I was thinking about using reflection at injection time to modify the values of the @QueryParam annotations, but wasn't sure if this was the best strategy to go with or even worth the overhead for such a tiny convenience. What approach do you guys think would be the best? If you want to see what I've added, my feature branch is [here](https://github.com/lulzWill/beadledom/tree/offset-based-paging).

**Comment by shiftyeyes** [comment]
@lulzWill Does your implementation allow for endpoints to have different defaults for limit? For example, one endpoint have a default limit of 100, and another have a limit of 1000?

**Comment by johnlcox** [comment]
Would using a custom `ParamConverter` instead of a `BeanParam` make it possible to customize the parameter names by injecting the names into the converter?

**Comment by lulzWill** [comment]
@shiftyeyes you can do this if you do not use the bean param. You would just have to populate the corresponding values within the list metadata object. The list metadata values will take precedence over the injected values if they are provided so you are able to have endpoints with varying default values as well as default field names.

@johnlcox I'm not very familiar with using `ParamConverter`, but I'll look into it and check back. From the quick glance I did of the documentation, it looks promising though.

**Comment by lulzWill** [comment]
@johnlcox got tied up working on some other stuff the past couple weeks, but got a chance to dive further into using the ParamConverter today. Unless I'm missing something, it looks like it would have the same issue as the bean param since both are just using the @QueryParam annotation to specify the field name. I'm gonna play around with the reflection approach a bit and see if I can come up with something that isn't really ugly.

**Comment by ikottman** [comment]
I took up @lulzWill work and added some tests/documentation and put out a PR. Some future work related to pagination that was explicitly _not_ covered by that PR is:
* Cursor based pagination - it can be added at a later date to the same module
* pagination is not compatible with generated clients - as discussed above the server representation of pagination is not directly compatible with the client representation. To work around this consumers can create an interface specifically for client consumption. To see an example of this in action, see the [integration tests in the PR](https://github.com/cerner/beadledom/pull/112/files#diff-90ccff6e55cb9f3915645b60afab02a0)
